import { getAppSetting } from '../db.mjs';
const value = (key) => { try { const db = getAppSetting(key); if (db !== undefined && db !== null) return String(db); } catch {} return process.env[key] ?? ''; };
const capKey = (cap, suffix) => `${String(cap).toUpperCase()}_${suffix}`;
export function customConfig(capability) { const p=String(capability).toUpperCase(); const baseURL=value(capKey(p,'BASE_URL')).trim().replace(/\/$/,''); const apiKey=value(capKey(p,'API_KEY')).trim(); const model=value(capKey(p,'MODEL')).trim(); if(!/^https?:\/\/[^\s/]+(?:\/[^\s]*)?$/i.test(baseURL)) throw new Error(`${p}_BASE_URL must be http(s) URL`); if(!model) throw new Error(`${p}_MODEL not configured`); if(!apiKey) throw new Error(`${p}_API_KEY not configured`); return {baseURL,apiKey,model}; }
async function post(cap,path,body,form=false){ const c=customConfig(cap); const headers={Authorization:`Bearer ${c.apiKey}`}; if(!form) headers['Content-Type']='application/json'; const r=await fetch(c.baseURL+path,{method:'POST',headers,body,signal:AbortSignal.timeout(30000)}); if(!r.ok) throw new Error(`custom ${cap} HTTP ${r.status}`); return r; }
export async function customVision(buf,mime='image/jpeg'){const c=customConfig('VISION'); const r=await post('VISION','/chat/completions',JSON.stringify({model:c.model,messages:[{role:'user',content:[{type:'image_url',image_url:{url:`data:${mime};base64,${buf.toString('base64')}`}},{type:'text',text:'请描述图片'}]}]})); return (await r.json()).choices?.[0]?.message?.content?.trim()||'';}
export async function customAsr(buf,mime='audio/wav'){const c=customConfig('ASR'); const fd=new FormData(); fd.append('file',new Blob([buf],{type:mime}),'audio.wav'); fd.append('model',c.model); return (await post('ASR','/audio/transcriptions',fd,true)).json().then(j=>j.text?.trim()||'');}
export async function customTts(text,opts={}){const c=customConfig('TTS'); const r=await post('TTS','/audio/speech',JSON.stringify({model:c.model,input:text,voice:opts.voice||value('TTS_VOICE_ID')||'alloy',response_format:'mp3'})); return Buffer.from(await r.arrayBuffer());}
export async function customImage(prompt,size='1024x1024'){const c=customConfig('IMAGE'); const d=await (await post('IMAGE','/images/generations',JSON.stringify({model:c.model,prompt,size,n:1,response_format:'b64_json'}))).json(); const x=d?.data?.[0]; if(x?.b64_json)return `data:image/png;base64,${x.b64_json}`; if(x?.url)return x.url; throw new Error('custom IMAGE empty response');}
export async function customEmbedding(text){const c=customConfig('EMBEDDING'); const d=await (await post('EMBEDDING','/embeddings',JSON.stringify({model:c.model,input:text}))).json(); return d.data?.[0]?.embedding||null;}
