const env = (k, fallback='') => process.env[k] || fallback;
export function customConfig(capability) {
 const p=String(capability).toUpperCase(); const url=env(`${p}_BASE_URL`, env('CUSTOM_RELAY_BASE_URL')); const key=env(`${p}_API_KEY`, env('CUSTOM_RELAY_API_KEY')); const model=env(`${p}_MODEL`, env('CUSTOM_RELAY_MODEL')); if(!/^https?:\/\/[^\s]+$/i.test(url)) throw new Error(`${p}_BASE_URL must be http(s) URL`); if(!key) throw new Error(`${p}_API_KEY not configured`); if(!model) throw new Error(`${p}_MODEL not configured`); return {baseURL:url.replace(/\/$/,''),apiKey:key,model};
}
async function call(cap,path,body,opts={}) { const c=customConfig(cap); const r=await fetch(`${c.baseURL}${path}`,{method:'POST',headers:{Authorization:`Bearer ${c.apiKey}`,'Content-Type':'application/json',...(opts.headers||{})},body,signal:AbortSignal.timeout(opts.timeout||30000)}); if(!r.ok) throw new Error(`custom ${cap} HTTP ${r.status}`); return r; }
export async function customVision(buf,mime='image/jpeg'){const r=await call('VISION','/chat/completions',JSON.stringify({model:customConfig('VISION').model,messages:[{role:'user',content:[{type:'image_url',image_url:{url:`data:${mime};base64,${buf.toString('base64')}`}},{type:'text',text:'请描述图片'}]}]})); return (await r.json()).choices?.[0]?.message?.content?.trim()||'';}
export async function customAsr(buf,mime='audio/wav'){const c=customConfig('ASR'); const fd=new FormData(); fd.append('file',new Blob([buf],{type:mime}),'audio.wav'); fd.append('model',c.model); const r=await fetch(`${c.baseURL}/audio/transcriptions`,{method:'POST',headers:{Authorization:`Bearer ${c.apiKey}`},body:fd,signal:AbortSignal.timeout(30000)}); if(!r.ok) throw new Error(`custom ASR HTTP ${r.status}`); return (await r.json()).text?.trim()||'';}
export async function customTts(text,opts={}){const c=customConfig('TTS'); const r=await call('TTS','/audio/speech',JSON.stringify({model:c.model,input:text,voice:opts.voice||env('TTS_VOICE_ID','alloy'),response_format:'mp3'})); return Buffer.from(await r.arrayBuffer());}
export async function customImage(prompt,size='1024x1024'){const c=customConfig('IMAGE'); const r=await call('IMAGE','/images/generations',JSON.stringify({model:c.model,prompt,size,n:1,response_format:'b64_json'})); const d=(await r.json()).data?.[0]; if(d?.b64_json)return `data:image/png;base64,${d.b64_json}`; if(d?.url)return d.url; throw new Error('custom IMAGE empty response');}
export async function customEmbedding(text){const c=customConfig('EMBEDDING'); const r=await call('EMBEDDING','/embeddings',JSON.stringify({model:c.model,input:text})); return (await r.json()).data?.[0]?.embedding||null;}
